
#SMOOTHING_WINDOW_SIZE = 5
ABSOLUTE_MAXIMUM_INSTANT_DISTANCE = 1500
ABSOLUTE_MAXIMUM_INSTANT_SPEED = 400
ABSOLUTE_MAXIMUM_INSTANT_ACCELERATION = 300
NOT_CONFIRMED_MALUS_DISTANCE = ABSOLUTE_MAXIMUM_INSTANT_DISTANCE * 1
MAX_MISSING_FRAME_BEFORE_DEAD = 200
MIN_SAMPLE_CONFIRMED_THRESHOLD = 10
MAX_FRAME_TO_CONFIRM_ELSE_GHOST = MIN_SAMPLE_CONFIRMED_THRESHOLD * 2